dist: focal
language: cpp
script:
- mkdir build
- cd build
- cmake ..
- cmake --build .
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: main
  script:
    - curl -T ip_filter-0.0.1-Linux.deb -ufezoo:$BINTRAY_API_KEY "https://api.bintray.com/content/fezoo/otuscpp/homework01/1/helloworld-0.0.1-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
