dist: focal
language: cpp
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install doxygen -y -qq
script:
  - git clone https://github.com/google/googletest.git gtest
  - cmake .
  - cmake --build .
  - doxygen doxygen.config
  - cmake --build . --target package
deploy:
- provider: script
  skip_cleanup: true
  keep_history: true
  on:
    branch: homework06
  script:
    - curl -T bulk-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ufezoo:$BINTRAY_API_KEY "https://api.bintray.com/content/fezoo/otuscpp/homework06/$TRAVIS_BUILD_NUMBER/bulk-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
- provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: html
  github_token: $GITHUB_TOKEN
  on:
   branch: homework06