language: cpp
before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install libboost-test-dev -y
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
script:
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: homework02
  script:
    - curl -T allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ufezoo:$BINTRAY_API_KEY "https://api.bintray.com/content/fezoo/otuscpp/homework02/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
